version: "2.4"
services:
  app:
    container_name: bot
    build: src
    ports:
      - 3390:3389
    restart: always
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env

volumes:
  data: